#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2024 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_aqua() {
  if cmd_exists aqua; then
    run_cmd aqua update-aqua
  else
    return "$C_DEP_NOTFOUND"
  fi
}
register_provider update_aqua aqua <<EOF
Declarative CLI Version Manager. Unify tool versions in teams, projects, and CI. Easy, painless, and secure.
Dependencies:
  - aqua (https://aquaproj.github.io/)
EOF
