#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_asdf() {
  if cmd_exists asdf; then
    run_cmd asdf update
    run_cmd asdf plugin-update --all
  else
    return $C_DEP_NOTFOUND
  fi
}
register_provider update_asdf asdf << EOF
Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more
Dependencies:
  - asdf (aur: asdf-vm) (https://github.com/asdf-vm/asdf)
EOF
