#!/bin/bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2020 Maddison Hellstrom (github.com/b0o)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_asdf() {
  if cmd_exists asdf; then
    run_cmd asdf update
    run_cmd asdf plugin-update --all
  else
    return $C_DEP_NOTFOUND
  fi
}
register_provider update_asdf asdf << EOF
Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more
Dependencies:
  - asdf (aur: asdf-vm) (https://github.com/asdf-vm/asdf)
EOF
