#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_cabal() {
  if cmd_exists cabal; then
    run_cmd cabal update
  else
    return "$C_DEP_NOTFOUND"
  fi
}
register_provider update_cabal cabal <<EOF
A system for building and packaging Haskell libraries and programs
Dependencies:
  - cabal-install (arch-repo: cabal-install) (https://github.com/haskell/cabal/blob/master/cabal-install/README.md)
EOF
