#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_cpan() {
  if cmd_exists cpan; then
    run_cmd cpan -u
  else
    return $C_DEP_NOTFOUND
  fi
}
register_provider update_cpan cpan << EOF
A repository of software modules written in the Perl programming language
Dependencies:
  - cpan (arch-repo: perl) (https://www.perl.org)
EOF
