#!/bin/bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_dummy() {
  log_msg "${Ifo}dummy"
  return 0
}
register_provider -h update_dummy dummy
