#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_gem() {
  if cmd_exists gem; then
    run_cmd gem update
  else
    return $C_DEP_NOTFOUND
  fi
}
register_provider update_gem gem << EOF
A package manager for the Ruby programming language
Dependencies:
  - gem (arch-repo: rubygems) (https://rubygems.org/)
EOF
