#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_gh() {
  if cmd_exists gh; then
    run_cmd gh extension upgrade --all
  else
    return "$C_DEP_NOTFOUND"
  fi
}
register_provider update_gh gh <<EOF
GitHub CLI extensions.
Dependencies:
  - gh (arch-repo: github-cli) (https://github.com/cli/cli)
EOF
