#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_npm() {
  if cmd_exists npm; then
    run_cmd npm --global install npm
    run_cmd npm --global update
  else
    return $C_DEP_NOTFOUND
  fi
}
register_provider update_npm npm << EOF
A package manager for Node.js / JavaScript
Dependencies:
  - npm (arch-repo: npm) (https://npmjs.com)
EOF
