#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_opam() {
  if cmd_exists opam; then
    run_cmd opam update
    run_cmd opam upgrade
  else
    return $C_DEP_NOTFOUND
  fi
}
register_provider update_opam opam << EOF
A package manager for the OCaml programming language
Dependencies:
  - opam (arch-repo: opam) (https://opam.ocaml.org/)
EOF
