#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_pip() {
  if cmd_exists pip; then
    local outdated
    outdated="$(pip list --user --outdated --format=freeze)" || return $C_UPDATE_ERR
    if [[ -n "$outdated" ]]; then
      echo "$outdated" > "$logdir/pip_${global_start_time}_freeze.txt"
      echo "$outdated" | sed 's/=.*$//' | while read -r pkg; do
        run_cmd pip install --user --upgrade "$pkg"
      done
    fi
  else
    return $C_DEP_NOTFOUND
  fi
  if cmd_exists pipx; then
    run_cmd pipx upgrade-all
  fi
}
register_provider update_pip pip << EOF
A package manager for the Python programming language
Dependencies:
  Primary:
    - pip (arch-repo: python-pip) (https://pip.pypa.io)
  Optional:
    - pipx (https://github.com/pipxproject/pipx)
EOF
