#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_rust() {
  local n=0
  if cmd_exists rustup; then
    n=$((n + 1))
    run_cmd rustup self upgrade-data
    # run_cmd rustup self update
    run_cmd rustup update
  fi
  if cmd_exists cargo; then
    n=$((n + 1))
    run_cmd cargo install-update -a
  fi
  [[ $n -gt 0 ]] || return $C_DEP_NOTFOUND
}
register_provider update_rust rust << EOF
A multi-paradigm system programming language
Dependencies:
  Primary: (at least one)
    - rustup (arch-repo: rustup) (https://rustup.rs/) (recommended)
      Rust toolchain installer
      Includes: cargo, rustup
    or
    - rust (arch-repo: rust) (https://www.rust-lang.org/)
      Rust toolchain
      Includes: cargo
  cargo crates:
    - cargo-update (https://github.com/nabijaczleweli/cargo-update)
      A cargo subcommand for checking and applying updates to installed executables
EOF
