#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2020 Maddison Hellstrom (github.com/b0o)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_rust() {
  local n=0
  if cmd_exists rustup; then
    n=$((n + 1))
    run_cmd rustup self upgrade-data
    # run_cmd rustup self update
    run_cmd rustup update
  fi
  if cmd_exists cargo; then
    n=$((n + 1))
    run_cmd cargo install-update -a
  fi
  [[ $n -gt 0 ]] || return $C_DEP_NOTFOUND
}
register_provider update_rust rust << EOF
A multi-paradigm system programming language
Dependencies:
  Primary: (at least one)
    - rustup (arch-repo: rustup) (https://rustup.rs/) (recommended)
      Rust toolchain installer
      Includes: cargo, rustup
    or
    - rust (arch-repo: rust) (https://www.rust-lang.org/)
      Rust toolchain
      Includes: cargo
  cargo crates:
    - cargo-update (https://github.com/nabijaczleweli/cargo-update)
      A cargo subcommand for checking and applying updates to installed executables
EOF
