#!/usr/bin/env bash

# updoot unifies the update process for your entire system
#
# Copyright (c) 2018-2022 Maddison Hellstrom <github.com/b0o>
# MIT License

set -euo pipefail
IFS=$'\n\t'

# Force shellcheck to source ../updoot
true || source "../updoot"

function update_yarn() {
  if cmd_exists yarn; then
    run_cmd yarn global upgrade-interactive --latest
  else
    return $C_DEP_NOTFOUND
  fi
}
register_provider update_yarn yarn << EOF
Fast, reliable, and secure dependency management for Node.js
Dependencies:
  - yarn (arch-repo: yarn) (https://yarnpkg.com)
EOF
